
Import('*')

SimObject('CombBase.py')
Source('CombBase.cc')
DebugFlag('CombBase', "For the base class for combinational blocks")

SimObject('SeqBase.py')
Source('SeqBase.cc')
DebugFlag('SeqBase', "For the base class for sequential blocks")

SimObject('CombMult.py')
Source('CombMult.cc')
DebugFlag('CombMult', "Comb multiplier")

SimObject('SeqMult.py')
Source('SeqMult.cc')
DebugFlag('SeqMult', "Seq multiplier")

SimObject('CombRead.py')
Source('CombRead.cc')
DebugFlag('CombRead', "To read from comb blocks")

SimObject('CombWrite.py')
Source('CombWrite.cc')
DebugFlag('CombWrite', "To write to comb blocks")

SimObject('CombAdd.py')
Source('CombAdd.cc')
DebugFlag('CombAdd', "Comb multiplier")

SimObject('SeqAdd.py')
Source('SeqAdd.cc')
DebugFlag('SeqAdd', "Seq multiplier")

SimObject('SeqReg.py')
Source('SeqReg.cc')
DebugFlag('SeqReg', "Seq register")

